plugins:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails
  - rubocop-capybara
  - rubocop-factory_bot

AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - db/schema.rb
    - bin/*
    - vendor/**/*
    - db/migrate/*.rb
    - config.ru
    - config/spring.rb
    - config/puma.rb
    - config/routes.rb
    - config/environment.rb
    - config/boot.rb
    - config/application.rb
    - config/environments/*.rb
    - config/initializers/*.rb

# Disabling warnings about line length because it's so common through
# the codebase currently. It would be good to fix as it would make things
# easier to read but it would take a bit of time to do.
# TODO: Enable this again
Layout/LineLength:
  Enabled: false

# We prefer double quotes here, and we're making liberal use of multi-line
# strings so it makes sense to enforce those to be consistent too
Style/StringLiterals:
  EnforcedStyle: double_quotes
  ConsistentQuotesInMultiline: true

# Putting separators in large numbers makes sense in some circumstances but
# in others (e.g. a database id) it's just nonsensical.
Style/NumericLiterals:
  Enabled: false

# For Rails, it feels a little overkill to require a description for
# each class, since so much is naming conventions.
Style/Documentation:
  Enabled: false

# We have names like division_senate_2009_12_30_8, which is reasonable
Naming/VariableNumber:
  Enabled: false

Style/FormatStringToken:
  EnforcedStyle: template

# Would be good to structure the Gemfile more and order it nicely
# TODO: Enable this
Bundler/OrderedGems:
  Exclude:
    - 'Gemfile'

# Disable a bunch of metrics to do with code complexity. These are all
# a bit hard-nosed. Maybe after a pass with Code Climate we can revisit.
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Metrics/ParameterLists:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false

# TODO: Get rid of these as soon as we can
RSpec/MultipleExpectations:
  Enabled: false
RSpec/MultipleMemoizedHelpers:
  Enabled: false
RSpec/NestedGroups:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
RSpec/IndexedLet:
  Enabled: false
RSpec/NoExpectationExample:
  Enabled: false

# Sign of a code smell that's non-trivial to fix, involves refactoring
# the code under test.
# TODO: Fix this
RSpec/SubjectStub:
  Enabled: false

# TODO: Fix this
Rails/HasAndBelongsToMany:
  Enabled: false

# TODO: Fix this
RSpecRails/InferredSpecType:
  Enabled: false

# TODO: Fix this
Rails/I18nLocaleTexts:
  Enabled: false
