#! /usr/bin/perl -w 
use strict;

# $Id: mpcoords2db.pl,v 1.1 2003/08/14 19:35:48 frabcus Exp $
# Converts mpcoords.txt file into database table

# The Public Whip, Copyright (C) 2003 Francis Irving and Julian Todd
# This is free software, and you are welcome to redistribute it under
# certain conditions.  However, it comes with ABSOLUTELY NO WARRANTY.
# For details see the file LICENSE.html in the top level of the source.

use POSIX qw(strftime);

require "../scraper/db.pm";
my $dbh = db::connect();

# Load number --> mp_id lookup tables
# (the mp_ids don't start at 1 and aren't sequential,
# but the ids which octave outputs are matrix row/column
# numbers, so do start at 1 and are sequential)
require "mpquery.pm";
my @mp_ixs = mpquery::get_mp_ixs($dbh);

db::query($dbh, "drop table if exists pw_cache_mpcoords");
db::query($dbh, 
"create table pw_cache_mpcoords (
    mp_id int not null,
    x float not null,
    y float not null,
    z float not null,
    unique(mp_id)
);");

$_ = <>;
my ($count, $eigx, $eigy, $eigz) = split(" ");
print <<END;
<?php
    # Generated by mpcoords2db.pl
    \$eigx = $eigx;
    \$eigy = $eigy;   
    \$eigz = $eigz;  
?>
END

while (<>)
{
    my ($mp, $x, $y, $z) = split(" ");
    my $mp_ix = $mp_ixs[$mp - 1];
#    print "ix $mp id $mp_ix pos $x $y $z\n";
    db::query($dbh, "insert into pw_cache_mpcoords (mp_id, x, y, z) values (?, ?, ?, ?)",
        $mp_ix, $x, $y, $z);
}


