# Only changing this so that it's more compatible with the html generated by the php app
# As soon as that's gone, we can get rid of this
Haml::Template.options[:attr_wrapper] = '"'

Haml::Filters.register_tilt_filter :Wiki
