<?php require_once "common.inc";

# $Id: election2007constituencies.php,v 1.1 2007/10/04 13:43:01 goatchurch Exp $

# The Public Whip, Copyright (C) 2003 Francis Irving and Julian Todd
# This is free software, and you are welcome to redistribute it under
# certain conditions.  However, it comes with ABSOLUTELY NO WARRANTY.
# For details see the file LICENSE.html in the top level of the source.


$wales_constituencies = array(
    "uk.org.publicwhip/cons/1" => 1,
    "uk.org.publicwhip/cons/9" => 1,
    "uk.org.publicwhip/cons/61" => 1,
    "uk.org.publicwhip/cons/79" => 1,
    "uk.org.publicwhip/cons/85" => 1,
    "uk.org.publicwhip/cons/104" => 1,
    "uk.org.publicwhip/cons/105" => 1,
    "uk.org.publicwhip/cons/112" => 1,
    "uk.org.publicwhip/cons/113" => 1,
    "uk.org.publicwhip/cons/114" => 1,
    "uk.org.publicwhip/cons/115" => 1,
    "uk.org.publicwhip/cons/117" => 1,
    "uk.org.publicwhip/cons/118" => 1,
    "uk.org.publicwhip/cons/124" => 1,
    "uk.org.publicwhip/cons/139" => 1,
    "uk.org.publicwhip/cons/140" => 1,
    "uk.org.publicwhip/cons/147" => 1,
    "uk.org.publicwhip/cons/163" => 1,
    "uk.org.publicwhip/cons/168" => 1,
    "uk.org.publicwhip/cons/255" => 1,
    "uk.org.publicwhip/cons/311" => 1,
    "uk.org.publicwhip/cons/351" => 1,
    "uk.org.publicwhip/cons/368" => 1,
    "uk.org.publicwhip/cons/370" => 1,
    "uk.org.publicwhip/cons/383" => 1,
    "uk.org.publicwhip/cons/384" => 1,
    "uk.org.publicwhip/cons/389" => 1,
    "uk.org.publicwhip/cons/398" => 1,
    "uk.org.publicwhip/cons/399" => 1,
    "uk.org.publicwhip/cons/440" => 1,
    "uk.org.publicwhip/cons/457" => 1,
    "uk.org.publicwhip/cons/462" => 1,
    "uk.org.publicwhip/cons/473" => 1,
    "uk.org.publicwhip/cons/569" => 1,
    "uk.org.publicwhip/cons/570" => 1,
    "uk.org.publicwhip/cons/582" => 1,
    "uk.org.publicwhip/cons/595" => 1,
    "uk.org.publicwhip/cons/596" => 1,
    "uk.org.publicwhip/cons/653" => 1,
    "uk.org.publicwhip/cons/658" => 1,
);

$scotland_constituencies = array(
    "uk.org.publicwhip/cons/2" => 1,
    "uk.org.publicwhip/cons/3" => 1,
    "uk.org.publicwhip/cons/4" => 1,
    "uk.org.publicwhip/cons/5" => 1,
    "uk.org.publicwhip/cons/11" => 1,
    "uk.org.publicwhip/cons/12" => 1,
    "uk.org.publicwhip/cons/18" => 1,
    "uk.org.publicwhip/cons/20" => 1,
    "uk.org.publicwhip/cons/106" => 1,
    "uk.org.publicwhip/cons/119" => 1,
    "uk.org.publicwhip/cons/122" => 1,
    "uk.org.publicwhip/cons/141" => 1,
    "uk.org.publicwhip/cons/142" => 1,
    "uk.org.publicwhip/cons/143" => 1,
    "uk.org.publicwhip/cons/160" => 1,
    "uk.org.publicwhip/cons/161" => 1,
    "uk.org.publicwhip/cons/162" => 1,
    "uk.org.publicwhip/cons/181" => 1,
    "uk.org.publicwhip/cons/182" => 1,
    "uk.org.publicwhip/cons/183" => 1,
    "uk.org.publicwhip/cons/184" => 1,
    "uk.org.publicwhip/cons/185" => 1,
    "uk.org.publicwhip/cons/186" => 1,
    "uk.org.publicwhip/cons/196" => 1,
    "uk.org.publicwhip/cons/198" => 1,
    "uk.org.publicwhip/cons/204" => 1,
    "uk.org.publicwhip/cons/207" => 1,
    "uk.org.publicwhip/cons/208" => 1,
    "uk.org.publicwhip/cons/209" => 1,
    "uk.org.publicwhip/cons/212" => 1,
    "uk.org.publicwhip/cons/210" => 1,
    "uk.org.publicwhip/cons/211" => 1,
    "uk.org.publicwhip/cons/225" => 1,
    "uk.org.publicwhip/cons/226" => 1,
    "uk.org.publicwhip/cons/238" => 1,
    "uk.org.publicwhip/cons/242" => 1,
    "uk.org.publicwhip/cons/243" => 1,
    "uk.org.publicwhip/cons/244" => 1,
    "uk.org.publicwhip/cons/245" => 1,
    "uk.org.publicwhip/cons/246" => 1,
    "uk.org.publicwhip/cons/247" => 1,
    "uk.org.publicwhip/cons/248" => 1,
    "uk.org.publicwhip/cons/249" => 1,
    "uk.org.publicwhip/cons/250" => 1,
    "uk.org.publicwhip/cons/251" => 1,
    "uk.org.publicwhip/cons/253" => 1,
    "uk.org.publicwhip/cons/260" => 1,
    "uk.org.publicwhip/cons/269" => 1,
    "uk.org.publicwhip/cons/270" => 1,
    "uk.org.publicwhip/cons/306" => 1,
    "uk.org.publicwhip/cons/316" => 1,
    "uk.org.publicwhip/cons/322" => 1,
    "uk.org.publicwhip/cons/344" => 1,
    "uk.org.publicwhip/cons/350" => 1,
    "uk.org.publicwhip/cons/379" => 1,
    "uk.org.publicwhip/cons/385" => 1,
    "uk.org.publicwhip/cons/388" => 1,
    "uk.org.publicwhip/cons/411" => 1,
    "uk.org.publicwhip/cons/420" => 1,
    "uk.org.publicwhip/cons/439" => 1,
    "uk.org.publicwhip/cons/444" => 1,
    "uk.org.publicwhip/cons/448" => 1,
    "uk.org.publicwhip/cons/449" => 1,
    "uk.org.publicwhip/cons/452" => 1,
    "uk.org.publicwhip/cons/481" => 1,
    "uk.org.publicwhip/cons/485" => 1,
    "uk.org.publicwhip/cons/548" => 1,
    "uk.org.publicwhip/cons/559" => 1,
    "uk.org.publicwhip/cons/588" => 1,
    "uk.org.publicwhip/cons/619" => 1,
    "uk.org.publicwhip/cons/632" => 1,
    "uk.org.publicwhip/cons/627" => 1,
);

$northern_ireland_constituencies = array(
    "uk.org.publicwhip/cons/35" => 1,
    "uk.org.publicwhip/cons/36" => 1,
    "uk.org.publicwhip/cons/37" => 1,
    "uk.org.publicwhip/cons/38" => 1,
    "uk.org.publicwhip/cons/192" => 1,
    "uk.org.publicwhip/cons/197" => 1,
    "uk.org.publicwhip/cons/231" => 1,
    "uk.org.publicwhip/cons/235" => 1,
    "uk.org.publicwhip/cons/325" => 1,
    "uk.org.publicwhip/cons/375" => 1,
    "uk.org.publicwhip/cons/400" => 1,
    "uk.org.publicwhip/cons/402" => 1,
    "uk.org.publicwhip/cons/406" => 1,
    "uk.org.publicwhip/cons/515" => 1,
    "uk.org.publicwhip/cons/519" => 1,
    "uk.org.publicwhip/cons/557" => 1,
    "uk.org.publicwhip/cons/593" => 1,
    "uk.org.publicwhip/cons/629" => 1,
);


