<?php
# $Id: election2008articles.inc,v 1.6 2008/10/21 18:48:29 publicwhip Exp $

# The Public Whip, Copyright (C) 2005 Francis Irving and Julian Todd
# This is free software, and you are welcome to redistribute it under
# certain conditions.  However, it comes with ABSOLUTELY NO WARRANTY.
# For details see the file LICENSE.html in the top level of the source.

# news articles linked to in the election2007 page

$newsarticleissues = array(
"Investigate Iraq" => array(
  array("publisher"=>"The Telegraph",
        "title"=>"Blair rules out Iraq inquiry before vote",
        "summary"=>"Tony Blair will defy Parliament and refuse to call an inquiry into the Iraq war even if MPs vote for an investigation in the Commons today.",
        "date"=>"1 November 2006",
        "url"=>"http://www.telegraph.co.uk/news/main.jhtml?xml=/news/2006/10/31/ninquiry31.xml"),

//  array("publisher"=>"BBC News",
//        "title"=>"Iraq inquiry call rejected",
//        "date"=>"1 November 2006",
//        "url"=>"http://news.bbc.co.uk/2/hi/uk_news/scotland/6096098.stm"),

  array("publisher"=>"The Sun",
        "title"=>"Blair sees off Iraq inquiry call",
        "summary"=>"Downing Street fought tooth and nail against any public inquiry, insisting that holding such a review while British troops are still fighting in Iraq would send a message of weakness to the insurgents.",
        "date"=>"31 October 2006",
        "url"=>"http://www.thesun.co.uk/article/0,,2-2006500444,00.html"),

  array("publisher"=>"BBC News",
        "title"=>"Tories urge Iraq inquiry support",
        "summary"=>"The Tories will call upon MPs to back the principle of an inquiry into the government's responsibilities in the war in Iraq.",
        "date"=>"11 June 2007",
        "url"=>"http://news.bbc.co.uk/2/hi/programmes/bbc_parliament/6741335.stm"),

//  array("publisher"=>"Associated Press",
//        "title"=>"Parliament rejects Iraq war decision probe",
//        "date"=>"11 June 2007",
//        "url"=>"http://www.usatoday.com/news/world/2007-06-11-britain-iraq_N.htm"),

  array("publisher"=>"The Sun",
        "title"=>"Gord: No early exit from Iraq",
        "summary"=>"Gordon Brown flew to Baghdad yesterday and vowed Britain will not cut and run from Iraq when he becomes PM.",
        "date"=>"12 June 2007",
        "url"=>"http://www.thesun.co.uk/article/0,,2-2007270137,00.html"),
),

"Invade Iraq" => array(
  array("publisher"=>"The Guardian",
        "title"=>"Containment is not working, Blair tells MPs",
        "summary"=>"\"Saddam Hussain's weapons of mass destruction programme is active, detailed and growing,\" Blair told an emergency session of the Commons.",
        "date"=>"24 September 2002",
        "url"=>"http://www.guardian.co.uk/world/2002/sep/24/iraq.uk"),
  array("publisher"=>"BBC",
        "title"=>"Iraq 'breaching UN resolution'",
        "summary"=>"US and British warplanes attacked Iraqi air-defence targets for the second day in a row on Sunday because they had been \"threatened\", US military chiefs said.",
        "date"=>"18 November 2002",
        "url"=>"http://news.bbc.co.uk/2/hi/middle_east/2489881.stm"),
  array("publisher"=>"The Times",
        "title"=>"Iraq dossier assembled by junior aides",
        "summary"=>"The Prime Minister's spokesman refused to say who had been responsible for the alleged plagiarism.",
        "date"=>"8 February 2003",
        "url"=>"http://www.timesonline.co.uk/tol/news/uk/article869123.ece"),
  array("publisher"=>"Daily Mail",
        "title"=>"MPs back Blair on war",
        "summary"=>"Tony Blair won Commons backing for war against Iraq but at the personal cost of another huge backbench rebellion.",
        "date"=>"18 March 2003",
        "url"=>"http://www.dailymail.co.uk/pages/live/articles/news/news.html?in_article_id=172464&in_page_id=1770"),
),

"Replace Trident" => array(
  array("publisher"=>"The Guardian",
        "title"=>"MPs vote to renew Trident",
        "summary"=>"Despite a massive Labour rebellion, MPs backed Tony Blair's bid to spend between £15bn and £20bn on new submarines to carry the Trident missiles.s.",
        "date"=>"14 March 2007",
        "url"=>"http://politics.guardian.co.uk/homeaffairs/story/0,,2033579,00.html"),

  array("publisher"=>"The Telegraph",
        "title"=>"Blair: Trident vote 'not last say' on deterrent",
        "summary"=>"Tony Blair has told MPs that if they vote to replace Trident today it will not be their last chance to debate whether Britain should renew its independent nuclear deterrent.",
        "date"=>"15 March 2007",
        "url"=>"http://www.telegraph.co.uk/news/main.jhtml?xml=/news/2007/03/14/ntrident414.xml"),

  array("publisher"=>"BBC News",
        "title"=>"Trident plan wins Commons support",
        "summary"=>"\"I believe it is important that we recognise that, although it is impossible to predict the future, the one thing... that is certain, is the unpredictability of it.\"",
        "date"=>"15 March 2007",
        "url"=>"http://news.bbc.co.uk/2/hi/uk_news/politics/6448173.stm"),

  array("publisher"=>"The Sun",
        "title"=>"Why I saved PM &amp; Gord's bacon",
        "summary"=>"THANKS to David Cameron, Tony Blair survived a 95-strong Labour revolt against replacing Britain.s Trident nuclear weapons system.",
        "date"=>"16 March 2007",
        "url"=>"http://www.thesun.co.uk/article/0,,2-2007120494,00.html"),
),

"Abolish Parliament" => array(
  array("publisher"=>"The Guardian",
        "title"=>"Reform bill could 'sweep away parliamentary debate'",
        "summary"=>"\"The government could rewrite almost any act and, in some cases, enact new laws that at present only parliament can make.\"",
        "date"=>"22 February 2006",
        "url"=>"http://politics.guardian.co.uk/constitution/story/0,,1715467,00.html"),
  array("publisher"=>"Wikipedia",
        "title"=>"Wikipedia: Legislative and Regulatory Reform Bill",
        "summary"=>"\"I give the House clear undertakings that the orders will not be used to implement highly controversial reforms.\"",
        "date"=>"",
        "url"=>"http://en.wikipedia.org/wiki/Legislative_and_Regulatory_Reform_Bill"),

  array("publisher"=>"BBC News",
        "title"=>"Government amends law change bill",
        "summary"=>"The bill was welcomed by the CBI, whose deputy director said it would bring crucial benefits for UK businesses.",
        "date"=>"4 May 2007",
        "url"=>"http://news.bbc.co.uk/2/hi/uk_news/politics/4971234.stm"),


  array("publisher"=>"BBC News",
        "title"=>"Ministers slammed on red tape law",
        "summary"=>"\"Ministers failed to recognise the constitutional impact of the plans.\"",
        "date"=>"8 June 2007",
        "url"=>"http://news.bbc.co.uk/2/hi/uk_news/politics/5058832.stm"),
),

"Public MPs" => array(
  array("publisher"=>"The Sun",
        "title"=>"MPs back 'squalid' secrecy bill",
        "summary"=>"MPs were today accused of trying to hide their expenses and allowances from the public.",
        "date"=>"18 May 2007",
        "url"=>"http://www.thesun.co.uk/article/0,,2-2007230065,00.html"),


  array("publisher"=>"Daily Mail",
        "title"=>"Labour MP's warning on freedom of information",
        "summary"=>"Labour party bosses are secretly plotting to exempt Parliament from freedom of information laws, one of their own MPs claimed.",
        "date"=>"10 May 2007",
        "url"=>"http://www.dailymail.co.uk/pages/live/articles/news/news.html?in_article_id=454006&in_page_id=1770&ito=newsnow"),
  array("publisher"=>"The Guardian",
        "title"=>"MP delays FoI exemption bill",
        "date"=>"27 April 2007",
        "summary"=>"\"Many of us believe that is just a ploy to bring their MPs in on May 18 so there will be over 100 to try and pass the bill.\"",
        "url"=>"http://politics.guardian.co.uk/foi/story/0,,2067084,00.html"),
  
  array("publisher"=>"BBC News",
        "title"=>"Brown will not block secrecy bid",
        "summary"=>"The MPs say they want to protect private letters from constituents - but critics say the move would also allow them to keep their expenses secret.",
        "date"=>"18 May 2007",
        "url"=>"http://news.bbc.co.uk/2/hi/uk_news/politics/6667431.stm"),

//  array("publisher"=>"The Times",
//        "title"=>"MPs vote to be exempt from law on freedom of information",
//        "date"=>"19 May 2007",
//        "url"=>"http://www.timesonline.co.uk/tol/news/politics/article1811271.ece"),

//  array("publisher"=>"The Telegraph",
//        "title"=>"Freedom of Information vote 'places MPs above law'",
//        "date"=>"19 May 2007",
//        "url"=>"http://www.telegraph.co.uk/news/main.jhtml?xml=/news/2007/05/19/nfoi19.xml"),
),

"Abortion" => array(
  array("publisher"=>"BBC",
        "title"=>"MPs reject cut in abortion limit", 
        "summary"=>"The upper time limit for abortions will remain at 24 weeks after MPs voted against proposals to reduce it.",
        "date"=>"21 May 2008",
        "url"=>"http://news.bbc.co.uk/1/hi/uk_politics/7412118.stm"),
  array("publisher"=>"The Times",
        "title"=>"Widespread disappointment at vote on abortion, says Cardinal", 
        "summary"=>"MPs are out of touch with public on abortion say Cardinal Murphy-O'Connor and Christian groups",
        "date"=>"21 May 2008",
        "url"=>"http://www.timesonline.co.uk/tol/comment/faith/article3980682.ece"),
  array("publisher"=>"Daily Mail",
        "title"=>"Britain is 'becoming the abortion capital of the world' claims Tory MP fighting to lower legal limit", 
        "summary"=>"Nadine Dorries MP is leading calls for a cut in the upper time limit for so-called \"social\" abortions from 24 weeks to 20.",
        "date"=>"6 May 2008",
        "url"=>"http://www.dailymail.co.uk/news/article-564225/Britain-abortion-capital-world-claims-Tory-MP-fighting-lower-legal-limit.html"),
),

"Planning reform" => array(
  array("publisher"=>"BBC",
        "title"=>"Ministers defeat planning rebels", 
        "summary"=>"The government has survived a Labour rebellion over plans to speed up the planning process for big projects such as airports and nuclear power stations.",
        "date"=>"25 June 2008", 
        "url"=>"http://news.bbc.co.uk/1/hi/uk_politics/7470846.stm"),
  array("publisher"=>"The Times", 
        "title"=>"The Planning Bill: a bulldozer through democracy",
        "summary"=>"Whatever happened to accountability? Decisions on big projects will be made by an unelected superquango", 
        "date"=>"26 June 2008",
        "url"=>"http://www.timesonline.co.uk/tol/comment/columnists/camilla_cavendish/article4214738.ece"),
  array("publisher"=>"The Independent",
        "title"=>"'Lights will go out' by 2015 if Lords rejects Planning Bill",
        "summary"=>"The CBI has urged the House of Lords to pass the Planning Bill, under consideration tomorrow, to help secure the nation's energy and infrastructure needs.",
        "date"=>"14 July 2008",
        "url"=>"http://www.independent.co.uk/news/business/news/lights-will-go-out-by-2015-if-lords-rejects-planning-bill-866957.html"),
),

"MPs' pay" => array(
  array("publisher"=>"BBC",
        "title"=>"MPs vote to keep homes expenses",
        "summary"=>"MPs have voted to keep their £24,000 second home allowances, but have decided not to award themselves above-inflation pay rises.",
        "date"=>"4 July 2008", 
        "url"=>"http://news.bbc.co.uk/1/hi/uk_politics/7486612.stm"),
  array("publisher"=>"The Sun",
        "title"=>"MPs vote against 4.4% pay rise",
        "summary"=>"MPs bowed to Government demands for restraint today and awarded themselves a 2.25 per cent pay rise for this year.",
        "date"=>"3 July 2008",
        "url"=>"http://www.thesun.co.uk/sol/homepage/news/article1375952.ece"),
  array("publisher"=>"The Independent",
        "title"=>"MPs swap 'John Lewis list' for 'Ikea list'",
        "summary"=>"MPs finally agreed to ditch the controversial \"John Lewis list\" today - but still clung to the right to kit out their second homes at the taxpayers' expense. ",
        "date"=>"16 July 2008",
        "url"=>"http://www.independent.co.uk/news/uk/politics/mps-swap-john-lewis-list-for-ikea-list-869084.html"),
),

"Ban smoking" => array(

  array("publisher"=>"The Sun",
        "title"=>"Pubs face total smoke ban",
        "summary"=>"A blanket ban on smoking moved a step closer yesterday when Tony Blair said Labour MPs would get a free vote on the issue.",
        "date"=>"12 January 2006",
        "url"=>"http://www.thesun.co.uk/article/0,,2-2006010758,00.html"),

  array("publisher"=>"The Guardian",
        "title"=>"MPs vote for blanket smoking ban next year",
        "summary"=>"A resounding cross-party majority of MPs yesterday rejected last minute compromises designed to exempt some pubs and private clubs.",
        "date"=>"15 February 2006",
        "url"=>"http://www.guardian.co.uk/smoking/Story/0,,1709946,00.html"),
  array("publisher"=>"Daily Mail",
        "title"=>"Stubbed out! Smoking ban from next summer",
        "date"=>"16 February 2006",
        "summary"=>"\"Today's vote will protect thousands of workers and save many lives.\"",
        "url"=>"http://www.dailymail.co.uk/pages/live/articles/news/news.html?in_article_id=377204&in_page_id=1770"),
  array("publisher"=>"BBC",
        "title"=>"MPs 'smoking in Commons toilets'",
        "summary"=>"Although it is not illegal to smoke in the Palace of Westminster, both Houses decided to ban it from Sunday - the same time as the rest of England.",
        "date"=>"5 July 2007",
        "url"=>"http://news.bbc.co.uk/2/hi/uk_news/politics/6273830.stm"),
),

"Ban fox hunting" => array(
  array("publisher"=>"The Guardian",
        "title"=>"Blair warns of 'all or nothing' hunt vote",
        "summary"=>"Tony Blair has delivered a blunt warning to Labour opponents of fox hunting that they risk losing a historic chance to outlaw the vast majority of hunts if they vote for an outright ban next week.",
        "date"=>"27 June 2003",
        "url"=>"http://www.guardian.co.uk/politics/2003/jun/27/hunting.immigrationpolicy"),
  array("publisher"=>"Daily Mail",
        "title"=>"MPs support foxhunting ban",
        "date"=>"1 July 2003",
        "summary"=>"Tony Blair suffered a humiliating setback last night when MPs voted decisively for an outright ban on foxhunting.",
        "url"=>"http://www.dailymail.co.uk/pages/live/articles/news/news.html?in_article_id=186800&in_page_id=1770"),
  array("publisher"=>"The Guardian",
        "title"=>"Invasion of the Commons",
        "summary"=>"The protest failed to stop mainly Labour MPs forcing through a bill banning hunting. Mr Blair, a previous opponent of fox hunting, did not vote.",
        "date"=>"16 September 2004",
        "url"=>"http://www.guardian.co.uk/politics/2004/sep/16/houseofcommons.hunting1"),
  array("publisher"=>"BBC",
        "title"=>"Q&amp;A: Hunting Bill",
        "summary"=>"The Parliament Act could only be invoked if the Lords voted to block the bill for a second time.",
        "date"=>"15 November 2004",
        "url"=>"http://news.bbc.co.uk/2/hi/uk_news/politics/3208106.stm"),
),

"Income tax" => array(
  array("publisher"=>"BBC",
        "title"=>"Lib Dems slam Budget tax changes",
        "summary"=>"Gordon Brown has \"asked the poor to subsidise the rich\" by cutting the basic rate of income tax and axing the 10p lower tax rate, the Lib Dems say.",
        "date"=>"21 March 2007",
        "url"=>"http://news.bbc.co.uk/2/hi/uk_news/politics/6475445.stm"),
  array("publisher"=>"BBC",
        "title"=>"Lower paid facing April tax rise",
        "summary"=>"More than five million households, many on minimum wage, will be worse off after tax changes that start in April next year.",
        "date"=>"1 December 2007",
        "url"=>"http://news.bbc.co.uk/2/hi/programmes/moneybox/7122894.stm"),
//  array("publisher"=>"The Times",
//        "title"=>"Tory 'toffs' stir mutiny in Crewe",
//        "date"=>"11 May 2008",
//        "url"=>"http://www.timesonline.co.uk/tol/news/politics/article3908519.ece"),
        
),


"Nuclear power" => array(
  array("publisher"=>"BBC",
        "title"=>"The nuclear debate",
        "summary"=>"Use this guide to explore the issues including waste, cost and energy alternatives.",
        "date"=>"9 January 2008",
        "url"=>"http://news.bbc.co.uk/2/hi/in_depth/sci_tech/2005/nuclear/default.stm"),
  array("publisher"=>"Daily Mail",
        "title"=>"Loan for troubled energy giant",
        "summary"=>"The Government stepped in with a £410 million support package for crisis-hit nuclear group British Energy",
        "date"=>"9 September 2002",
        "url"=>"http://www.dailymail.co.uk/pages/live/articles/news/news.html?in_article_id=137383&in_page_id=1770"),
  array("publisher"=>"BBC",
        "title"=>"Nuclear energy 'too uneconomic'",
        "summary"=>"LibDem environment spokesman said any expansion would divert essential funding from renewable sources, such as water and wind farms.",
        "date"=>"17 January 2006",
        "url"=>"http://news.bbc.co.uk/2/hi/uk_news/politics/4620072.stm"),
  array("publisher"=>"The Guardian",
        "title"=>"Tory adviser says nuclear power should be last resort",
        "summary"=>"David Cameron's environmental policy adviser has warned the Conservative party against an unthinking embrace of nuclear power.",
        "date"=>"18 January 2006",
        "url"=>"http://www.guardian.co.uk/politics/2006/jan/18/conservatives.uk"),
),

"Parliament protest" => array(
  array("publisher"=>"Wikipedia",
        "title"=>"Serious Organised Crime and Police Act 2005 - Protests near Parliament",
        "summary"=>"The Act is controversial primarily for the restriction of the right to demonstrate within an exclusion zone of up to one kilometre from any point in Parliament Square.",
        "date"=>"",
        "url"=>"http://en.wikipedia.org/wiki/Serious_Organised_Crime_and_Police_Act_2005#Protests_near_Parliament"),
  array("publisher"=>"Daily Mail",
        "title"=>"Anti-war protester wins High Court battle",
        "summary"=>"Anti-war protester Brian Haw today won his High Court battle against new laws threatening to end his 24-hour vigil outside Parliament, which has now gone on for four years.",
        "date"=>"29 July 2005",
        "url"=>"http://www.dailymail.co.uk/pages/live/articles/news/news.html?in_article_id=357522&in_page_id=1770"),
  array("publisher"=>"BBC",
        "title"=>"Arrests at Parliament protest ban",
        "summary"=>"Six people have been arrested as about 100 campaigners staged a protest in Parliament Square against the Serious Organised Crime and Police Act.",
        "date"=>"7 August 2005",
        "url"=>"http://news.bbc.co.uk/2/hi/uk_news/england/london/4742589.stm"),
  array("publisher"=>"The Guardian",
        "title"=>"So many causes, so little time",
        "summary"=>"Unless you have permission, it's illegal to demonstrate near the Houses of Parliament. But that wasn't going to stop Mark Thomas, who set out to make a record number of protests in one day.",
        "date"=>"12 October 2006",
        "url"=>"http://www.guardian.co.uk/politics/2006/oct/12/houseofcommons.comment"),
),

"Control orders" => array(
  array("publisher"=>"BBC",
        "title"=>"Q&amp;A: Terror law row explained",
        "summary"=>"The control orders would range from tagging suspects to placing them under what is effectively house arrest.",
        "date"=>"12 March 2005",
        "url"=>"http://news.bbc.co.uk/2/hi/uk_news/politics/4288407.stm"),
  array("publisher"=>"Wikipedia",
        "title"=>"Control orders",
        "summary"=>"Terrorist allegations against certain individuals are of such a nature and from such sources that they cannot be prosecuted \"because that would mean revealing sensitive and dangerous intelligence\"",
        "date"=>"",
        "url"=>"http://en.wikipedia.org/wiki/Control_order"),
  array("publisher"=>"Daily Mail",
        "title"=>"Terror bill passed after mass rebellion",
        "summary"=>"The Tories branded control orders \"unpleasant, repellent and disgusting\".",
        "date"=>"1 March 2005",
        "url"=>"http://www.dailymail.co.uk/pages/live/articles/news/news.html?in_article_id=339609&in_page_id=1770"),
  array("publisher"=>"The Guardian",
        "title"=>"Chaos as first terror orders are issued",
        "summary"=>"Suspects must phone a private tagging company before they leave the house.",
        "date"=>"13 March 2005",
        "url"=>"http://www.guardian.co.uk/uk/2005/mar/13/september11.terrorism"),
),

"Post offices" => array(
  array("publisher"=>"BBC",
        "title"=>"Post vote slashes Labour majority",
        "summary"=>"\"The government has always underestimated the strength of anger on Labour benches against the privatisation and cuts in this essential public service.\"",
        "date"=>"19 March 2008",
        "url"=>"http://news.bbc.co.uk/2/hi/uk_news/politics/7303968.stm"),
  array("publisher"=>"The Guardian",
        "title"=>"Pleas ignored as 600 town post offices go",
        "summary"=>"The Post Office is planning to shut more than 600 branches over the next three months despite protests by MPs and pensioner groups.",
        "date"=>"18 December 2004",
        "url"=>"http://www.guardian.co.uk/uk/2004/dec/18/money.politics"),
  array("publisher"=>"Daily Mail",
        "title"=>"3,000 post offices may close",
        "summary"=>"Sub-postmasters were today considering a restructuring plan which could lead to the closure of 3,000 post offices in towns and cities across the UK.",
        "date"=>"10 April 2002",
        "url"=>"http://www.dailymail.co.uk/pages/live/articles/news/news.html?in_article_id=109008&in_page_id=1770"),
  array("publisher"=>"The Guardian",
        "summary"=>"MPs last night overwhelmingly endorsed government proposals to rescue Britain's ailing postal service with a £210m package of subsidies that will allow the closure of up to 3,000 urban sub-post offices deemed surplus to modern consumer needs..",
        "title"=>"Closure of 3,000 sub-post offices endorsed",
        "date"=>"16 October 2002",
         "url"=>"http://www.guardian.co.uk/uk/2002/oct/16/post.lucyward"),
),



"ID Cards" => array(
  array("publisher"=>"Daily Mail",
        "title"=>"Blair in appeal to head off ID cards rebellion",
        "summary"=>"Blair will say guaranteeing security is as important to the Labour Party as creating a fairer and more just society.",
        "date"=>"10 February 2006",
        "url"=>"http://www.dailymail.co.uk/pages/live/articles/news/news.html?in_article_id=376761&in_page_id=1770"),
  array("publisher"=>"BBC",
        "title"=>"Peers demand total ID card cost",
        "summary"=>"\"Surely Parliament is entitled to know the total cost, which of course includes the cost to other departments who are going to use the scheme.\"",
        "date"=>"16 November 2005",
        "url"=>"http://news.bbc.co.uk/2/hi/uk_news/politics/4443592.stm"),
  array("publisher"=>"BBC",
        "title"=>"MPs reject ID card costings call",
        "summary"=>"MPs also backed making it compulsory for people to be given cards - and put on a register - when they apply for passports.",
        "date"=>"14 February 2006",
        "url"=>"http://news.bbc.co.uk/2/hi/uk_news/politics/4707608.stm"),
//  array("publisher"=>"BBC",
//        "title"=>"Where now for ID cards?",
//        "date"=>"16 March 2006",
//        "url"=>"http://news.bbc.co.uk/2/hi/uk_news/politics/4804528.stm"),
  array("publisher"=>"BBC",
        "title"=>"Labour survives ID card rebellion",
        "summary"=>"Charles Clarke said the bill would not remove civil liberties but give people more control over their identities.",
        "date"=>"18 October 2005",
        "url"=>"http://news.bbc.co.uk/2/hi/uk_news/politics/4354886.stm"),
),

"University tuition fees" => array(
  array("publisher"=>"The Guardian", 
        "title"=>"Faltering rebellion that brought Blair to the brink",
        "summary"=>"A day of drama, intrigue and betrayal saw the tuition fees rebellion fade, but not until the government had been taken to the brink of calamity.",
        "date"=>"28 January 2004",
        "url"=>"http://www.guardian.co.uk/politics/2004/jan/28/uk.highereducation2"),
//  array("publisher"=>"The Guardian",
//        "title"=>"Fee rebels to seek fresh concessions",
//        "date"=>"29 January 2004",
//        "url"=>"http://www.guardian.co.uk/politics/2004/jan/29/uk.studentpolitics"),
  array("publisher"=>"BBC",
        "title"=>"Q&amp;A: Tuition fees vote",
        "summary"=>"Opponants complain of a two-tier system and students being priced out of higher education.",
        "date"=>"20 March 2004",
        "url"=>"http://news.bbc.co.uk/2/hi/uk_news/education/3582121.stm"),
  array("publisher"=>"BBC",
        "title"=>"Rebels lose top-up fee protest",
        "summary"=>"Education Secretary Charles Clarke said he believed the vote was \"a vote for the future of higher education and this country\".",
        "date"=>"31 March 2004",
        "url"=>"http://news.bbc.co.uk/2/hi/uk_news/politics/3587263.stm"),
  array("publisher"=>"The Guardian",
        "title"=>"MPs give final approval to top-up fees",
        "summary"=>"The higher education bill, which contains the controversial provision for universities to charge up to £3,000 a year in fees, is now certain to gain Royal Assent this summer..",
        "date"=>"1 July 2004",
        "url"=>"http://education.guardian.co.uk/higher/news/story/0,,1251638,00.html"),
),

);


function StrArticle($newsarticle)
{
    # we have the option to mark up date as pretty date
    return '<a hREF="'.$newsarticle["url"].'" class="newslink" target="_blank">'.
           $newsarticle["title"].'</a> <b>'.$newsarticle["publisher"].'</b> '.($newsarticle["date"] ? '('.$newsarticle["date"].')' : '');
}

function WriteShortListNews($issuename)
{
    global $newsarticleissues;
    $newsarticles = $newsarticleissues[$issuename];
    if (!$newsarticles)
        return;
    $i = 1;
    foreach ($newsarticles as $newsarticle)
    {
        print ' <a href="'.$newsarticle["url"].'"';
        print ' onmouseover="Tip(\''.$newsarticle["title"].' - '.$newsarticle["publisher"].' ('.$newsarticle["date"].')\')">'; 
        print "[$i]</a>\n";
        $i += 1;
    }
}

function WriteLongListNews($issuename)
{
    global $newsarticleissues;
    $newsarticles = $newsarticleissues[$issuename];
    #print "<a onclick=\"shownews('$newsid', this)\" class=\"shownews\">show news</a>\n";
    #print "<div id=\"$newsid\" style=\"display:none\">\n";
    print "<div class=\"newsart\">\n";
    print "<p><b>Some newspaper stories from the day...</b></p>";

    print "<ul>\n";
    if ($newsarticles)
    {
        foreach ($newsarticles as $newsarticle)
        {
            print "<li>\n";
            if ($newsarticle["summary"])
            {
                if ($newsarticle["date"])
                    print $newsarticle["date"]." - ";
                print "<b>".$newsarticle["title"]."</b> ";
                print "(".$newsarticle["publisher"].") ";
                print "<p class=\"summ\"><i>".$newsarticle["summary"]."</i>";
                print " (<a href=\"".$newsarticle["url"]."\" target=\"_blank\" title=\"Read rest of article\">more...</a>)</p>\n";
            }
            else
            {
                print '<a href="'.$newsarticle["url"].'" class="newslink" target="_blank">';
                print $newsarticle["title"];
                print '</a> <b>'.$newsarticle["publisher"].'</b> ';
                if ($newsarticle["date"])
                    print '('.$newsarticle["date"].')';
            }
            print "</li>\n";
        }
    }
    else
        print "<li>No news articles yet.</li>\n";

    print "</ul>\n";
    print "</div>\n";
}


