<?php
# $Id: election2008articles.inc,v 1.3 2008/05/09 19:46:27 publicwhip Exp $

# The Public Whip, Copyright (C) 2005 Francis Irving and Julian Todd
# This is free software, and you are welcome to redistribute it under
# certain conditions.  However, it comes with ABSOLUTELY NO WARRANTY.
# For details see the file LICENSE.html in the top level of the source.

# news articles linked to in the election2007 page

$newsarticleissues = array(
"Investigate Iraq" => array(
  array("publisher"=>"The Telegraph",
        "title"=>"Blair rules out Iraq inquiry before vote",
        "date"=>"1 November 2006",
        "url"=>"http://www.telegraph.co.uk/news/main.jhtml?xml=/news/2006/10/31/ninquiry31.xml"),

  array("publisher"=>"BBC News",
        "title"=>"Iraq inquiry call rejected",
        "date"=>"1 November 2006",
        "url"=>"http://news.bbc.co.uk/2/hi/uk_news/scotland/6096098.stm"),

  array("publisher"=>"The Sun",
        "title"=>"Blair sees off Iraq inquiry call",
        "date"=>"31 October 2006",
        "url"=>"http://www.thesun.co.uk/article/0,,2-2006500444,00.html"),

  array("publisher"=>"BBC News",
        "title"=>"Tories urge Iraq inquiry support",
        "date"=>"11 June 2007",
        "url"=>"http://news.bbc.co.uk/2/hi/programmes/bbc_parliament/6741335.stm"),

  array("publisher"=>"Associated Press",
        "title"=>"Parliament rejects Iraq war decision probe",
        "date"=>"11 June 2007",
        "url"=>"http://www.usatoday.com/news/world/2007-06-11-britain-iraq_N.htm"),

  array("publisher"=>"The Sun",
        "title"=>"Gord: No early exit from Iraq",
        "date"=>"12 June 2007",
        "url"=>"http://www.thesun.co.uk/article/0,,2-2007270137,00.html"),
),

"Replace Trident" => array(
  array("publisher"=>"The Guardian",
        "title"=>"MPs vote to renew Trident",
        "date"=>"14 March 2007",
        "url"=>"http://politics.guardian.co.uk/homeaffairs/story/0,,2033579,00.html"),

  array("publisher"=>"The Telegraph",
        "title"=>"Blair: Trident vote 'not last say' on deterrent",
        "date"=>"15 March 2007",
        "url"=>"http://www.telegraph.co.uk/news/main.jhtml?xml=/news/2007/03/14/ntrident414.xml"),

  array("publisher"=>"BBC News",
        "title"=>"Trident plan wins Commons support",
        "date"=>"15 March 2007",
        "url"=>"http://news.bbc.co.uk/2/hi/uk_news/politics/6448173.stm"),

  array("publisher"=>"The Sun",
        "title"=>"Why I saved PM &amp; Gord's bacon",
        "date"=>"16 March 2007",
        "url"=>"http://www.thesun.co.uk/article/0,,2-2007120494,00.html"),
),

"Abolish Parliament" => array(
  array("publisher"=>"Wikipedia",
        "title"=>"Wikipedia: Legislative and Regulatory Reform Bill",
        "date"=>"",
        "url"=>"http://en.wikipedia.org/wiki/Legislative_and_Regulatory_Reform_Bill"),

  array("publisher"=>"BBC News",
        "title"=>"Government amends law change bill",
        "date"=>"4 May 2007",
        "url"=>"http://news.bbc.co.uk/2/hi/uk_news/politics/4971234.stm"),

  array("publisher"=>"The Guardian",
        "title"=>"Reform bill could 'sweep away parliamentary debate'",
        "date"=>"22 February 2006",
        "url"=>"http://politics.guardian.co.uk/constitution/story/0,,1715467,00.html"),

  array("publisher"=>"BBC News",
        "title"=>"Ministers slammed on red tape law",
        "date"=>"8 June 2007",
        "url"=>"http://news.bbc.co.uk/2/hi/uk_news/politics/5058832.stm"),
),

"Public MPs" => array(
  array("publisher"=>"BBC News",
        "title"=>"Brown will not block secrecy bid",
        "date"=>"18 May 2007",
        "url"=>"http://news.bbc.co.uk/2/hi/uk_news/politics/6667431.stm"),

  array("publisher"=>"The Times",
        "title"=>"MPs vote to be exempt from law on freedom of information",
        "date"=>"19 May 2007",
        "url"=>"http://www.timesonline.co.uk/tol/news/politics/article1811271.ece"),

  array("publisher"=>"The Guardian",
        "title"=>"MP delays FoI exemption bill",
        "date"=>"27 April 2007",
        "url"=>"http://politics.guardian.co.uk/foi/story/0,,2067084,00.html"),

  array("publisher"=>"Daily Mail",
        "title"=>"Labour MP's warning on freedom of information",
        "date"=>"10 May 2007",
        "url"=>"http://www.dailymail.co.uk/pages/live/articles/news/news.html?in_article_id=454006&in_page_id=1770&ito=newsnow"),

  array("publisher"=>"The Telegraph",
        "title"=>"Freedom of Information vote 'places MPs above law'",
        "date"=>"19 May 2007",
        "url"=>"http://www.telegraph.co.uk/news/main.jhtml?xml=/news/2007/05/19/nfoi19.xml"),

  array("publisher"=>"The Sun",
        "title"=>"MPs back 'squalid' secrecy bill",
        "date"=>"18 May 2007",
        "url"=>"http://www.thesun.co.uk/article/0,,2-2007230065,00.html"),
),

"Ban smoking" => array(
  array("publisher"=>"Daily Mail",
        "title"=>"Stubbed out! Smoking ban from next summer",
        "date"=>"16 February 2006",
        "url"=>"http://www.dailymail.co.uk/pages/live/articles/news/news.html?in_article_id=377204&in_page_id=1770"),

  array("publisher"=>"The Sun",
        "title"=>"Pubs face total smoke ban",
        "date"=>"12 January 2006",
        "url"=>"http://www.thesun.co.uk/article/0,,2-2006010758,00.html"),

  array("publisher"=>"The Guardian",
        "title"=>"MPs vote for blanket smoking ban next year",
        "date"=>"15 February 2006",
        "url"=>"http://www.guardian.co.uk/smoking/Story/0,,1709946,00.html"),
  array("publisher"=>"BBC",
        "title"=>"MPs 'smoking in Commons toilets'",
        "date"=>"5 July 2007",
        "url"=>"http://news.bbc.co.uk/2/hi/uk_news/politics/6273830.stm"),
),

"Ban fox hunting" => array(
  array("publisher"=>"Daily Mail",
        "title"=>"MPs support foxhunting ban",
        "date"=>"1 July 2003",
        "url"=>"http://www.dailymail.co.uk/pages/live/articles/news/news.html?in_article_id=186800&in_page_id=1770"),
  array("publisher"=>"The Guardian",
        "title"=>"Invasion of the Commons",
        "date"=>"16 September 2004",
        "url"=>"http://www.guardian.co.uk/politics/2004/sep/16/houseofcommons.hunting1"),
  array("publisher"=>"The Guardian",
        "title"=>"Blair warns of 'all or nothing' hunt vote",
        "date"=>"27 June 2003",
        "url"=>"http://www.guardian.co.uk/politics/2003/jun/27/hunting.immigrationpolicy"),
  array("publisher"=>"BBC",
        "title"=>"Q&amp;A: Hunting Bill",
        "date"=>"15 November 2004",
        "url"=>"http://news.bbc.co.uk/2/hi/uk_news/politics/3208106.stm"),
),

"Nuclear power" => array(
  array("publisher"=>"BBC",
        "title"=>"The nuclear debate",
        "date"=>"",
        "url"=>"http://news.bbc.co.uk/2/hi/in_depth/sci_tech/2005/nuclear/default.stm"),
  array("publisher"=>"Daily Mail",
        "title"=>"Loan for troubled energy giant",
        "date"=>"9 September 2002",
        "url"=>"http://www.dailymail.co.uk/pages/live/articles/news/news.html?in_article_id=137383&in_page_id=1770"),
  array("publisher"=>"BBC",
        "title"=>"Nuclear energy 'too economic'",
        "date"=>"17 January 2006",
        "url"=>"http://news.bbc.co.uk/2/hi/uk_news/politics/4620072.stm"),
  array("publisher"=>"The Guardian",
        "title"=>"Tory adviser says nuclear power should be last resort",
        "date"=>"18 January 2006",
        "url"=>"http://www.guardian.co.uk/politics/2006/jan/18/conservatives.uk"),
),

"Parliament protest" => array(
  array("publisher"=>"Wikipedia",
        "title"=>"Serious Organised Crime and Police Act 2005 - Protests near Parliament",
        "date"=>"",
        "url"=>"http://en.wikipedia.org/wiki/Serious_Organised_Crime_and_Police_Act_2005#Protests_near_Parliament"),
  array("publisher"=>"Daily Mail",
        "title"=>"Anti-war protester wins High Court battle",
        "date"=>"29 July 2005",
        "url"=>"http://www.dailymail.co.uk/pages/live/articles/news/news.html?in_article_id=357522&in_page_id=1770"),
  array("publisher"=>"BBC",
        "title"=>"Arrests at Parliament protest ban",
        "date"=>"7 August 2005",
        "url"=>"http://news.bbc.co.uk/2/hi/uk_news/england/london/4742589.stm"),
  array("publisher"=>"The Guardian",
        "title"=>"So many causes, so little time",
        "date"=>"12 October 2006",
        "url"=>"http://www.guardian.co.uk/politics/2006/oct/12/houseofcommons.comment"),
),

"Control orders" => array(
  array("publisher"=>"Wikipedia",
        "title"=>"Control orders",
        "date"=>"",
        "url"=>"http://en.wikipedia.org/wiki/Control_order"),
  array("publisher"=>"The Guardian",
        "title"=>"Chaos as first terror orders are issued",
        "date"=>"13 March 2005",
        "url"=>"http://www.guardian.co.uk/uk/2005/mar/13/september11.terrorism"),
  array("publisher"=>"Daily Mail",
        "title"=>"Terror bill passed after mass rebellion",
        "date"=>"1 March 2005",
        "url"=>"http://www.dailymail.co.uk/pages/live/articles/news/news.html?in_article_id=339609&in_page_id=1770"),
  array("publisher"=>"BBC",
        "title"=>"Q&amp;A: Terror law row explained",
        "date"=>"12 March 2005",
        "url"=>"http://news.bbc.co.uk/2/hi/uk_news/politics/4288407.stm"),
),

"Post offices" => array(
  array("publisher"=>"BBC",
        "title"=>"Post vote slashes Labour majority",
        "date"=>"19 March 2008",
        "url"=>"http://news.bbc.co.uk/2/hi/uk_news/politics/7303968.stm"),
  array("publisher"=>"The Guardian",
        "title"=>"Pleas ignored as 600 town post offices go",
        "date"=>"18 December 2004",
        "url"=>"http://www.guardian.co.uk/uk/2004/dec/18/money.politics"),
  array("publisher"=>"Daily Mail",
        "title"=>"3,000 post offices may close",
        "date"=>"10 April 2002",
        "url"=>"http://www.dailymail.co.uk/pages/live/articles/news/news.html?in_article_id=109008&in_page_id=1770"),
  array("publisher"=>"The Guardian",
        "title"=>"Closure of 3,000 sub-post offices endorsed",
        "date"=>"16 October 2002",
        "url"=>"http://www.guardian.co.uk/uk/2002/oct/16/post.lucyward"),
),



"ID Cards" => array(
  array("publisher"=>"Daily Mail",
        "title"=>"Blair in appeal to head off ID cards rebellion",
        "date"=>"10 February 2006",
        "url"=>"http://www.dailymail.co.uk/pages/live/articles/news/news.html?in_article_id=376761&in_page_id=1770"),
  array("publisher"=>"BBC",
        "title"=>"Peers demand total ID card cost",
        "date"=>"16 November 2005",
        "url"=>"http://news.bbc.co.uk/2/hi/uk_news/politics/4443592.stm"),
  array("publisher"=>"BBC",
        "title"=>"MPs reject ID card costings call",
        "date"=>"14 February 2006",
        "url"=>"http://news.bbc.co.uk/2/hi/uk_news/politics/4707608.stm"),
  array("publisher"=>"BBC",
        "title"=>"Where now for ID cards?",
        "date"=>"16 March 2006",
        "url"=>"http://news.bbc.co.uk/2/hi/uk_news/politics/4804528.stm"),
  array("publisher"=>"BBC",
        "title"=>"Labour survives ID card rebellion",
        "date"=>"18 October 2005",
        "url"=>"http://news.bbc.co.uk/2/hi/uk_news/politics/4354886.stm"),
),

"University tuition fees" => array(
  array("publisher"=>"The Guardian", 
        "title"=>"Faltering rebellion that brought Blair to the brink",
        "date"=>"28 January 2004",
        "url"=>"http://www.guardian.co.uk/politics/2004/jan/28/uk.highereducation2"),
  array("publisher"=>"The Guardian",
        "title"=>"Fee rebels to seek fresh concessions",
        "date"=>"29 January 2004",
        "url"=>"http://www.guardian.co.uk/politics/2004/jan/29/uk.studentpolitics"),
  array("publisher"=>"The Guardian",
        "title"=>"MPs give final approval to top-up fees",
        "date"=>"1 July 2004",
        "url"=>"http://education.guardian.co.uk/higher/news/story/0,,1251638,00.html"),
  array("publisher"=>"BBC",
        "title"=>"Q&amp;A: Tuition fees vote",
        "date"=>"20 March 2004",
        "url"=>"http://news.bbc.co.uk/2/hi/uk_news/education/3582121.stm"),
  array("publisher"=>"BBC",
        "title"=>"Rebels lose top-up fee protest",
        "date"=>"31 March 2004",
        "url"=>"http://news.bbc.co.uk/2/hi/uk_news/politics/3587263.stm"),
),

);


function StrArticle($newsarticle)
{
    # we have the option to mark up date as pretty date
    return '<a href="'.$newsarticle["url"].'" class="newslink" target="_blank">'.
           $newsarticle["title"].'</a> <b>'.$newsarticle["publisher"].'</b> '.($newsarticle["date"] ? '('.$newsarticle["date"].')' : '');
}

function WriteShortListNews($issuename)
{
    global $newsarticleissues;
    $newsarticles = $newsarticleissues[$issuename];
    if (!$newsarticles)
        return;
    $i = 1;
    foreach ($newsarticles as $newsarticle)
    {
        print ' <a href="'.$newsarticle["url"].'"';
        print ' onmouseover="Tip(\''.$newsarticle["title"].' - '.$newsarticle["publisher"].' ('.$newsarticle["date"].')\')">'; 
        print "[$i]</a>\n";
        $i += 1;
    }
}

function WriteLongListNews($issuename)
{
    global $newsarticleissues;
    $newsarticles = $newsarticleissues[$issuename];
    #print "<a onclick=\"shownews('$newsid', this)\" class=\"shownews\">show news</a>\n";
    #print "<div id=\"$newsid\" style=\"display:none\">\n";
    print "<ul class=\"newsart\">\n";
    if (!$newsarticles)
        print "<li>No news articles yet.</li>\n";
    else
    {
    foreach ($newsarticles as $newsarticle)
    {
        print "<li>\n";
        print StrArticle($newsarticle);
        print "</li>\n";
    }
    }
    print "</ul>\n";
    #print "</div>\n";
}


