<?php
# $Id: election2008articles.inc,v 1.2 2008/05/03 11:54:03 publicwhip Exp $

# The Public Whip, Copyright (C) 2005 Francis Irving and Julian Todd
# This is free software, and you are welcome to redistribute it under
# certain conditions.  However, it comes with ABSOLUTELY NO WARRANTY.
# For details see the file LICENSE.html in the top level of the source.

# news articles linked to in the election2007 page

$newsarticleissues = array(
"Investigate Iraq" => array(
  array("publisher"=>"The Telegraph",
        "title"=>"Blair rules out Iraq inquiry before vote",
        "date"=>"1 November 2006",
        "url"=>"http://www.telegraph.co.uk/news/main.jhtml?xml=/news/2006/10/31/ninquiry31.xml"),

  array("publisher"=>"BBC News",
        "title"=>"Iraq inquiry call rejected",
        "date"=>"1 November 2006",
        "url"=>"http://news.bbc.co.uk/2/hi/uk_news/scotland/6096098.stm"),

  array("publisher"=>"The Sun",
        "title"=>"Blair sees off Iraq inquiry call",
        "date"=>"31 October 2006",
        "url"=>"http://www.thesun.co.uk/article/0,,2-2006500444,00.html"),

  array("publisher"=>"BBC News",
        "title"=>"Tories urge Iraq inquiry support",
        "date"=>"11 June 2007",
        "url"=>"http://news.bbc.co.uk/2/hi/programmes/bbc_parliament/6741335.stm"),

  array("publisher"=>"Associated Press",
        "title"=>"Parliament rejects Iraq war decision probe",
        "date"=>"11 June 2007",
        "url"=>"http://www.usatoday.com/news/world/2007-06-11-britain-iraq_N.htm"),

  array("publisher"=>"The Sun",
        "title"=>"Gord: No early exit from Iraq",
        "date"=>"12 June 2007",
        "url"=>"http://www.thesun.co.uk/article/0,,2-2007270137,00.html"),
),

"Replace Trident" => array(
  array("publisher"=>"The Guardian",
        "title"=>"MPs vote to renew Trident",
        "date"=>"14 March 2007",
        "url"=>"http://politics.guardian.co.uk/homeaffairs/story/0,,2033579,00.html"),

  array("publisher"=>"The Telegraph",
        "title"=>"Blair: Trident vote 'not last say' on deterrent",
        "date"=>"15 March 2007",
        "url"=>"http://www.telegraph.co.uk/news/main.jhtml?xml=/news/2007/03/14/ntrident414.xml"),

  array("publisher"=>"BBC News",
        "title"=>"Trident plan wins Commons support",
        "date"=>"15 March 2007",
        "url"=>"http://news.bbc.co.uk/2/hi/uk_news/politics/6448173.stm"),

  array("publisher"=>"The Sun",
        "title"=>"Why I saved PM &amp; Gord's bacon",
        "date"=>"16 March 2007",
        "url"=>"http://www.thesun.co.uk/article/0,,2-2007120494,00.html"),
),

"Abolish Parliament" => array(
  array("publisher"=>"Wikipedia",
        "title"=>"Wikipedia: Legislative and Regulatory Reform Bill",
        "date"=>"",
        "url"=>"http://en.wikipedia.org/wiki/Legislative_and_Regulatory_Reform_Bill"),

  array("publisher"=>"BBC News",
        "title"=>"Government amends law change bill",
        "date"=>"4 May 2007",
        "url"=>"http://news.bbc.co.uk/2/hi/uk_news/politics/4971234.stm"),

  array("publisher"=>"The Guardian",
        "title"=>"Reform bill could 'sweep away parliamentary debate'",
        "date"=>"22 February 2006",
        "url"=>"http://politics.guardian.co.uk/constitution/story/0,,1715467,00.html"),

  array("publisher"=>"BBC News",
        "title"=>"Ministers slammed on red tape law",
        "date"=>"8 June 2007",
        "url"=>"http://news.bbc.co.uk/2/hi/uk_news/politics/5058832.stm"),
),

"Public MPs" => array(
  array("publisher"=>"BBC News",
        "title"=>"Brown will not block secrecy bid",
        "date"=>"18 May 2007",
        "url"=>"http://news.bbc.co.uk/2/hi/uk_news/politics/6667431.stm"),

  array("publisher"=>"The Times",
        "title"=>"MPs vote to be exempt from law on freedom of information",
        "date"=>"19 May 2007",
        "url"=>"http://www.timesonline.co.uk/tol/news/politics/article1811271.ece"),

  array("publisher"=>"The Guardian",
        "title"=>"MP delays FoI exemption bill",
        "date"=>"27 April 2007",
        "url"=>"http://politics.guardian.co.uk/foi/story/0,,2067084,00.html"),

  array("publisher"=>"Daily Mail",
        "title"=>"Labour MP's warning on freedom of information",
        "date"=>"10 May 2007",
        "url"=>"http://www.dailymail.co.uk/pages/live/articles/news/news.html?in_article_id=454006&in_page_id=1770&ito=newsnow"),

  array("publisher"=>"The Telegraph",
        "title"=>"Freedom of Information vote 'places MPs above law'",
        "date"=>"19 May 2007",
        "url"=>"http://www.telegraph.co.uk/news/main.jhtml?xml=/news/2007/05/19/nfoi19.xml"),

  array("publisher"=>"The Sun",
        "title"=>"MPs back 'squalid' secrecy bill",
        "date"=>"18 May 2007",
        "url"=>"http://www.thesun.co.uk/article/0,,2-2007230065,00.html"),
),

"Ban smoking" => array(
  array("publisher"=>"Daily Mail",
        "title"=>"Stubbed out! Smoking ban from next summer",
        "date"=>"16 February 2006",
        "url"=>"http://www.dailymail.co.uk/pages/live/articles/news/news.html?in_article_id=377204&in_page_id=1770"),

  array("publisher"=>"The Sun",
        "title"=>"Pubs face total smoke ban",
        "date"=>"12 January 2006",
        "url"=>"http://www.thesun.co.uk/article/0,,2-2006010758,00.html"),

  array("publisher"=>"The Guardian",
        "title"=>"MPs vote for blanket smoking ban next year",
        "date"=>"15 February 2006",
        "url"=>"http://www.guardian.co.uk/smoking/Story/0,,1709946,00.html"),
),

"Nuclear power" => array(
  array("publisher"=>"BBC",
        "title"=>"The nuclear debate",
        "date"=>"",
        "url"=>"http://news.bbc.co.uk/2/hi/in_depth/sci_tech/2005/nuclear/default.stm"),
),

);


function StrArticle($newsarticle)
{
    # we have the option to mark up date as pretty date
    return '<a href="'.$newsarticle["url"].'" class="newslink" target="_blank">'.
           $newsarticle["title"].'</a> <b>'.$newsarticle["publisher"].'</b> ('.$newsarticle["date"].')';
}

function WriteShortListNews($issuename)
{
    global $newsarticleissues;
    $newsarticles = $newsarticleissues[$issuename];
    if (!$newsarticles)
        return;
    $i = 1;
    foreach ($newsarticles as $newsarticle)
    {
        print ' <a href="'.$newsarticle["url"].'"';
        print ' onmouseover="Tip(\''.$newsarticle["title"].' - '.$newsarticle["publisher"].' ('.$newsarticle["date"].')\')">'; 
        print "[$i]</a>\n";
        $i += 1;
    }
}

function WriteLongListNews($issuename)
{
    global $newsarticleissues;
    $newsarticles = $newsarticleissues[$issuename];
    #print "<a onclick=\"shownews('$newsid', this)\" class=\"shownews\">show news</a>\n";
    #print "<div id=\"$newsid\" style=\"display:none\">\n";
    print "<ul class=\"newsart\">\n";
    if (!$newsarticles)
        print "<li>No news articles yet.</li>\n";
    else
    {
    foreach ($newsarticles as $newsarticle)
    {
        print "<li>\n";
        print StrArticle($newsarticle);
        print "</li>\n";
    }
    }
    print "</ul>\n";
    #print "</div>\n";
}


