<?php
# $Id: s8-footer.inc,v 1.1 2005/02/22 10:49:00 sams Exp $

# The Public Whip, Copyright (C) 2003 Francis Irving and Julian Todd
# This is free software, and you are welcome to redistribute it under
# certain conditions.  However, it comes with ABSOLUTELY NO WARRANTY.
# For details see the file LICENSE.html in the top level of the source.

?>

<!-- the end of the major content -->
</td></tr>

<!-- the footer section -->
<tr class="headers"><td bgcolor="#003300" colspan="2"><p class="footer">
<span class="footerright">
<a title="Details on the free license for this data" href="/faq.php#legal">Legal information</a>
</span>
</p></td></tr>

<!-- hold the maximum width of the content -->
</table>

</center>
</body>
</html>
